{% set name = "xontrib-readable-traceback" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b5e841f0aa32dc941741cda784b67d5a4434352a4b9ffdd2da2cdb1dce850ebf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - colorama
    - python-backtrace
    - xonsh

test:
  commands:
    - test -f "${SP_DIR}/xontrib/readable-traceback.xsh"

about:
  home: https://github.com/6syun9/xontrib-readable-traceback
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Make traceback easier to see for xonsh

extra:
  recipe-maintainers:
    - scopatz
