travis:
  secure:
    BINSTAR_TOKEN: Mt+v0x6/wMvnnH7g1l/9BOYNwx+xGB+86+RqsPvkaVkawEf5v9gT+5u6Zn3X7UzrzrjPjyUxPBcv3KIFk2ARpE+Sf4JYrqQL2ukcJkCtbualomRi16LM2BzJjqQrdvrnctWwTJAqzWJzwrCbSvYoy2TIIJ33JmD+/AuF/6om1qC3VEf8y2ywhNolEwAUNxF0a6OQYDZudZelNiFF4D1b5xoo0pxa+xngOlVHOAeIMjg5QUypXZUGgMTXPi4sIhkxgawKxo/KcqNZj5MicyuiL8ATE1zDo8eZoY7cUyIAyvWlof8J21TqpcH/hjz9IOu+G9AYfA2+Gq22dU7W9lwlGf6FwsI9vB7bCkfnEp252Q8fOunGw8GYU+WAIbxW27M4LX1MpvQRu8ox6GnyqrPLNYLuUry6qTkvBwCEOhXU+nOaBnGNugVGrbpAa7VK2J0wxZ7g7ZgTUrcwCNrWStplSYYBTuu1izIfeOJcThY7iEwoTf6dvGoVDeJvHZpliWWwOSQYiXzg+Es23G38nkfR59MOeGQyXDjCYSffIfCrBDtsV4esLVrs3zISRcV9Np+gqJCXsnejOGtm5cdRiHeQDptZVFFJtse1GkMGWQsZRqtiYRtRgIFTJ9ZbedhxUlygooi2mtSMvRdT9Ll1A1gpwLT9JzruvkX4hJpqXYY5uFc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
